### ISSUE TITLE
Error: Node returned status: 403. Probably java isnt running

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#12]
I got this after added a node
![frontend](http://i.imgur.com/Hgx4hUh.png)

When i access ip:9001 on backend, I got this
![backend](http://i.imgur.com/Jj64rMz.png)

**Comment by erindru** [comment]
What did you enter for the `api_key` when adding the node? And does it match the value of `backend.base.api_key` in the openseedbox-server config file?

**Comment by psycholyzern** [comment]
I leave default value "vml' and enter vml too when adding the node.
you said transmission is required. I installed transmission via apt-get, do I need to do any customisation to the transmission's config file?

**Comment by drew442** [comment]
you need to make sure transmission daemon isn't running and make sure it doesn't start at boot time

sudo service transmission-daemon stop
sudo update-rc.d tomcat disable

**Comment by psycholyzern** [comment]
I am confused with the transmission part.
Can I install transmission via apt-get?
How can the script interact with transmission without knowing the username and password of transmission? 

Im using Ubuntu 14.04.

Btw sorry for the late reply.

**Comment by drew442** [comment]
Yes. You can install it from apt-get. Just make sure to stop it and remove it from automatically starting.

**Comment by erindru** [comment]
FYI the script doesn't interact with transmission without knowing its username and password - you configure it as part of adding a node
And yeah @drew442 is right, you have to stop it from starting automatically. This is because Openseedbox starts it itself with certain parameters, and it doesnt check to see if its already started. If you have two transmission-daemons running, then things break
