### ISSUE TITLE
How adding torrent to multi-backend working?

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#26]
I have 2 backend curerntly. I see that openseedbox filling my 1st backend and not touching 2nd backend. Is this how it is working? Or it should add the torrent randomly to both backend?

**Comment by erindru** [comment]
You've stumbled on something that I never actually managed to complete. Currently a "Plan" is tied to a specific backend, and a user is tied to a plan. So you can have multiple users each with their own backend. This was "good enough" in my flatting situation where I could just tell my flatmates to pay for their own VPS and I could set it up so any torrents they downloaded went to their own VPS instead of mine.

But you're right, a proper torrent scheduling algorithm would be ideal. I could never decide on what i should look like - if you scheduled based on available space, you need to know the total torrent size up front (impossible with magnet links). You also run the risk of one node serving hundreds of small torrents, and another node serving a few large torrents.

If you schedule based on "number of torrents", you run the risk of running one of your nodes out of space because one node could have 3 small torrents on it and the other could have 3 large torrents.

I came to the conclusion that I needed a combination of both, but I needed to know the total size of the torrent up front before making a scheduling decision. This meant I had to either drop support for magnet links, or create a "magnet to torrent" converter.

I have tried several times to make a "magnet to torrent" converter but I never seem to finish the project or get it into a working state.

**Comment by psycholyzern** [comment]
Instead checking torrent size, maybe you can check actual size of the disk? You can use percentage to balance then.

DiskA = used/total*100 //used space in percent
DiskB = used/total*100 //used space in percent

if DiskA>DiskB then
  put.torrent.in = diskB

This is just a concept. I don't know about language you used so I don't know the real environment about it.

This will balance the space used.
