### ISSUE TITLE
CleanupJobs not cleaning

### ISSUE THREAD

**Issue by sweatbar** [erindru/openseedbox#35]
Hey even though i removed a file after downloading it doesn't delete that file from the source path . (gone from the panel but still available in the directory ) and in admin panel clean up directory it shows as Cleanup Job 	0 s 	0 	false ,
How to fix this?
Tried to run clean up job manually by clicking run but same results

![clean](https://cloud.githubusercontent.com/assets/9255451/11142597/9291dd64-8a14-11e5-86ad-343d0f826e84.PNG)

**Comment by erindru** [comment]
The cleanup job is disabled and should really be removed (see https://github.com/erindru/openseedbox/blob/master/app/com/openseedbox/jobs/CleanupJob.java#L27).

This is because there were some race conditions with it where it would clean up legitimate torrents after they had been added to Openseedbox but before they had been added to Transmission.

Unfortunately this means that you have to perform the cleanup manually if Openseedbox gets out of sync with the state of transmission-daemon. You can do this by accessing the transmission-daemon web interface directly on your node and deleting the torrents there that dont show up in the Openseedbox UI.
