### ISSUE TITLE
Installed at 2 machine

### ISSUE THREAD

**Issue by laukaleong** [erindru/openseedbox#39]
Both showed this message when I visit

![oops](https://cloud.githubusercontent.com/assets/17609670/13488580/147c6610-e15d-11e5-8371-ea1b25a4a604.JPG)

What could go wrong?

**Comment by erindru** [comment]
Ah yes, i've been trying to figure out what was causing that, it seems to be an issue in Play. Its not anything you're doing, the current Docker image is broken and I have not yet had time to fix it.

Pull requests are always welcome if you'd like to have a go at fixing it yourself, otherwise i'm hoping to have some time next week to try and get it sorted

**Comment by erindru** [comment]
Ok I think I found the issue, it was to do with the nginx config. Try now. Note that the README has been updated with new image names and a few other tweaks so it might pay to quickly go over it again
