### ISSUE TITLE
Backend up "no"

### ISSUE THREAD

**Issue by wesleynunes121** [erindru/openseedbox#8]
backend its working, but when i try create a node I get the message backend up "NO" can you help-me?
![sem titulo](https://cloud.githubusercontent.com/assets/9297984/6884280/5c7ec8e0-d5bf-11e4-8d2a-157906e8dcfc.png)

**Comment by erindru** [comment]
"Backend" here is referring to a running transmission-daemon on the node. If everything is set up correctly, you should be able to click the 'restart backend' button, which is directly to the right of the 'no' text. If you installed transmission-daemon from a package manager, make sure that there isnt an instance already running and that its disabled from running on startup - Openseedbox starts its own transmissions-daemon and if there's one already running then the two will conflict and no downloads will start

**Comment by wesleynunes121** [comment]
Yeah ! i fixed thanks, but the NodePollerJob don't working, i deleted condition "if (n.isReachable())." but he not do anything yet, your project is awesome!

![assf](https://cloud.githubusercontent.com/assets/9297984/6886927/843bd960-d626-11e4-9f77-5efc796f32b6.png)
![sem titulo](https://cloud.githubusercontent.com/assets/9297984/6886944/1c724a98-d627-11e4-94a1-257f7fa1d855.png)

**Comment by wesleynunes121** [comment]
I put back that piece and now it is only in "Downloading"

// if (n.isReachable()) {
List<ITorrent> torrents = n.getNodeBackend().listTorrents();
List<Torrent> fromDb = Torrent.getByHash(getHashStrings(torrents));
for (Torrent db : fromDb) {
ITorrent match = findMatching(db, torrents);
if (match != null) {
db.merge(match);
}
}
Torrent.batch().update(fromDb);
// }

![134](https://cloud.githubusercontent.com/assets/9297984/6887144/bc1b15ca-d62c-11e4-9696-1077a8dc4c9e.png)

**Comment by erindru** [comment]
On your node, what is the output of `ps -A | grep transmission`. If there's two transmission-daemons running, then they will clobber each other and the downloads wont start.
The fact that the torrent went from "Metadata Downloading" to "Downloading" is positive though, that means that NodePollerJob did run successfully at least once

**Comment by erindru** [comment]
The other thing you can do is check the built-in Transmission Web UI on your node to see what its reporting

**Comment by wesleynunes121** [comment]
Woooooooooooooooooow ! Is Working! i'm so happy
I will translate it for Brazilian Portuguese
thank you, very much xD

![akjfajfsa](https://cloud.githubusercontent.com/assets/9297984/6887440/69c07d1a-d636-11e4-863a-901ffbbde19e.png)

**Comment by wesleynunes121** [comment]
one more thing, when I change plans or delete, happens it .. what can it be?

![11234324123](https://cloud.githubusercontent.com/assets/9297984/6887495/6d05736c-d637-11e4-90ed-01c7660aba7a.png)

**Comment by erindru** [comment]
Hey awesome to see you got it working!

Hmm not sure, probably a bug :) that part of the code is like 4 years old now, on my personal instance I set up the plans once and never changed them so its not really well tested either

**Comment by wesleynunes121** [comment]
where the files are saved? I searched the folder that we appointed in backend.base.path and is not it, and also not in the standard transmission-daemon, you tell me where it is being saved files? and you can do direct download? my does not work

**Comment by wesleynunes121** [comment]
I found the files, they are in media/openseedbox, as I do to enable the direct download of the interface?

**Comment by erindru** [comment]
The way direct download from the interface works is, you need to set up a web server (apache, nginx although I recommend nginx) to serve the files. The interface then redirects the browser to a URL that matches up to where the webserver is serving the files from. Thats's what Step 9 of "Installing the Backend" is

If you click the link to a file in the interface, and you get a 404, look at the URL in the address bar. That is where Openseedbox thinks the file should be located, so you need to configure your webserver to serve files from that location. There is a sample nginx config included, https://github.com/erindru/openseedbox/blob/master/conf/openseedbox.nginx.conf

**Comment by wesleynunes121** [comment]
conf/openseedbox.nginx.conf, I have to put these settings in /src/nginx-1.2.6/conf, right? and also one for openseedbox-server

**Comment by erindru** [comment]
Oh yes you're right, sorry the sample nginx config for the *backend* is https://github.com/erindru/openseedbox-server/blob/master/conf/openseedbox-server.nginx.conf
You'll need to make sure that nginx is loading this config file when it starts up, typically you'd delete any sample sites from your existing nginx config and include it in the main nginx config file.

You'll need to modify it to turn of SSL if you arent using SSL, and you might need to change or omit the server_name directive depending on your setup.

The nginx sample config in the main repository (not openseedbox-server) is only required if you're serving the interface over nginx as well

The reason why nginx is required at all is that its much more efficient to serve files using a proper webserver, rather than using the built-in webserver that comes with Play!

**Comment by wesleynunes121** [comment]
I changed the nginx.conf to yours, but when I try to reload the server it asks something more

"nginx -s reload
nginx: [emerg] "server" directive is not allowed here in /etc/nginx/nginx.conf:1"

I've never worked with nginx, just with apache but I have no idea how to implement it in your project

**Comment by erindru** [comment]
right, the sample config supplied here is intended to be "included" in the main nginx config file (that comes with nginx). the sample config just supplies the "server" directives, it is not a full config file. When you installed nginx, it should have come with a config file. Within the `http` block, use an `include` directive to include the config supplied with openseedbox (which you might still need to modify for your environment).

Alternatively, you can still use Apache, just set the document root to /media/openseedbox/complete to serve files from there

**Comment by wesleynunes121** [comment]
openseedbox-server.nginx.conf I put
in "server_name" I put "myserver:9001", created new ssl_certificate and ssl_certificate_key in proxy_pass I put "myserver:9001"

and nginx.conf I put an include redirecting to openseedbox-server.nginx.conf

I need to make some more changes? nginx server is already running on my localhost
![1234](https://cloud.githubusercontent.com/assets/9297984/6889083/d7668af2-d664-11e4-945e-fb256300194c.png)
![12353251231](https://cloud.githubusercontent.com/assets/9297984/6889086/dafe89d0-d664-11e4-9724-8dd20e699973.png)

**Comment by erindru** [comment]
That config looks good actually, however you dont put :9001 at the end, thats the port your Play! server is listening on and not nginx (your nginx is listening on 443 as per the 'listen' directive).

I think you can remove the server_name directive entirely since you're not using a DNS name.

**Comment by wesleynunes121** [comment]
okay, I removed the server_name, and everything seems okay, but I still can't direct download interface, you can tell me what missing? I think only lack this last configuration thank you !

**Comment by erindru** [comment]
When you try and download a file from the interface, what URL is it trying to load?

**Comment by wesleynunes121** [comment]
when download finish, i click on "download" then i click on file, but he don

**Comment by wesleynunes121** [comment]
When i try acess http://176.31.248.92:9001/download he shows me " GET /download " i think the "include" is working, and nginx is doing the service.

but when I try to do a download, example: http://176.31.248.92:9001/download/c3bb80a3846c6401537d65fa00093d7211c90ba3?name=The.Walking.Dead.S05E15.720p.HDTV.x264-IMMERSE%2FThe.Walking.Dead.S05E15.720p.HDTV.x264-IMMERSE.mkv

he does not start

![134](https://cloud.githubusercontent.com/assets/9297984/6901094/5e44db9c-d6e1-11e4-985e-45baf03228ee.png)

**Comment by erindru** [comment]
Ok, what I think you need to do is change your Node Hostname (in the admin or direct in the database if the admin proves to be too buggy) to point to port 443 instead of 9001 and check the https checkbox since you're using SSL

What happens here is, the backend is expecting to be run through a webserver like nginx instead of directly from the builtin Play! server. The builtin Play! server triggers the file download, but it does this by sending a X-Accel-Redirect header containing the location of the file, which nginx picks up and starts the file download. Thats what the proxy directive for / in the nginx config is, its redirecting requests to to the Play! webserver

**Comment by wesleynunes121** [comment]
yes, it worked but at the same time did not work, when I click on download, it sends me the following link:
(this link does not work because this part is in lowercase 2f1854acebf01fa1ba129c2e622427698ed250b6)

https://176.31.248.92/download/2f1854acebf01fa1ba129c2e622427698ed250b6?name=Revenge.S04E18.HDTV.x264-LOL%5Bettv%5D%2Frevenge.418.hdtv-lol.mp4

(but when I manually change to 2F1854ACEBF01FA1BA129C2E622427698ED250B6 it works)

https://176.31.248.92/download/2F1854ACEBF01FA1BA129C2E622427698ED250B6?name=Revenge.S04E18.HDTV.x264-LOL%5Bettv%5D%2Frevenge.418.hdtv-lol.mp4

why he is sending me in lowercase, not the correct?

**Comment by wesleynunes121** [comment]
I found, when add torrent with magnet he does it, that strange no?
when add from file, he does right

**Comment by erindru** [comment]
Yep, what you've found is a known bug that I havent been too bothered to fix :) what happens is, the info_hash specified in the magnet is taken as gospel even if it doesnt match up to the info_hash on the actual torrent once the magnet is resolved to a torrent. Transmission downloads to a directory named after the info_hash on the torrent. So if the two dont match up, the direct download links break. For this reason, adding torrents from file is more reliable. Feel free to submit a pull request :)

Also, I have had some trouble in the past with UTF-8 filenames, so if direct downloads appear broken on torrents with foreign characters in the filename, its most likely caused by that

**Comment by erindru** [comment]
Also, I think you're the only person in the world to make it this far with getting openseedbox running, so if you have any ideas for improvements I am interested to know

**Comment by wesleynunes121** [comment]
I have many ideas on how to improve the openseedbox, but I do not have much experience in Java development, I also think I could not fix the info_hash bug, but if you are interested in donations to continue working with the project, I would be happy in to donate

**Comment by wesleynunes121** [comment]
you will continue to improve the project? if you have a means of better communication, just tell me and thanks for the help.

**Comment by erindru** [comment]
To be honest I haven't been working on it much at all recently, its built on a pretty old technology stack now (Play 1.x is in maintenance mode and effectively abandoned). It meets my personal needs so the only major change its really had in the past 2 years was switching from OpenID to OpenID Connect for login when Google turned off its OpenID endpoint. Several times I have attempted a "from-scratch" rewrite but each time its ended in failure because I have so little time to work on it and the current version still works with a little prodding :)

**Comment by wesleynunes121** [comment]
okay, thank you anything call me.
